_BASE_: "base/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/ql-b423/sda/TXH/model_weigth/detectron2/cascade.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  STEPS: (16000, 19000)
  MAX_ITER: 20000
