_BASE_: "base/Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "/home/ql-b423/sda/TXH/model_weigth/detectron2/mask_x_3.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
SOLVER:
  STEPS: (16000, 19000)
  MAX_ITER: 20000